### ISSUE TITLE
Error in dimmer configuration

### ISSUE THREAD

**Issue by lassem** [ruebox/openhab2-addons#19]
I suspect this is the reason for the somewhat weird UI on dimmer switches?

https://github.com/ruebox/openhab2-addons/blob/88c0ff78a709f3489a01f026670f1311c1bf463c/addons/binding/org.openhab.binding.freeathome/ESH-INF/thing/thing-types.xml#L295

**Comment by ruebox** [comment]
Hi,
just fixed it. There will be a slider from 0 - 100 %. If you provide 100 as a number, the light is completly up and with 0 completely dark?

**Comment by ruebox** [comment]
are all other things properly working?
