### ISSUE TITLE
1 channel motion sensor device id 900A

### ISSUE THREAD

**Issue by lassem** [ruebox/openhab2-addons#22]
```xml
        <device shortSerialNumber="LKO" nameId="FFF5" functionId="FEFA" iconId="FFF5" softwareVersion="0.1.6"
                deviceId="900A" domainAddress="CFCC" compilerVersion="006B9313" buildNumber="00000027" isTp="true"
                serialNumber="ABB700C714C3" commissioningState="ready" copyId="a" progress="100">
            <attribute name="busVoltage">28.635</attribute>
            <attribute name="deviceErrors">0</attribute>
            <attribute name="deviceReboots">6</attribute>
            <attribute name="displayName">Garasje</attribute>
            <attribute name="floor">01</attribute>
            <attribute name="offsetX">0.116060293135436</attribute>
            <attribute name="offsetY">0.0669249112339988</attribute>
            <attribute name="operationTime">4268</attribute>
            <attribute name="room">17</attribute>
            <channels>
                <channel mask="FFFFFFFF" nameId="0122" sameLocation="true" i="ch0000" cid="ABB70303">
                    <attribute name="functionId">11</attribute>
                    <attribute name="offsetX">0.40504064166377546</attribute>
                    <attribute name="offsetY">0.5183702225419059</attribute>
                    <attribute name="selectedIcon">52</attribute>
                    <inputs>
                        <dataPoint i="idp0000" full="false">
                            <value>0</value>
                        </dataPoint>
                    </inputs>
                    <outputs>
                        <dataPoint i="odp0000" full="false">
                            <value>1</value>
                        </dataPoint>
                        <dataPoint i="odp0001" full="false">
                            <value>0</value>
                        </dataPoint>
                    </outputs>
                    <parameters>
                        <parameter i="pm0000">
                            <value>2</value>
                        </parameter>
                    </parameters>
                    <scenes/>
                </channel>
                <channel mask="FFFFFFFF" nameId="004F" i="ch0001" cid="ABB70148">
                    <attribute name="displayName">Lys i tak</attribute>
                    <attribute name="floor">01</attribute>
                    <attribute name="functionId">7</attribute>
                    <attribute name="offsetX">0.509647404771568</attribute>
                    <attribute name="offsetY">0.419671410926401</attribute>
                    <attribute name="room">17</attribute>
                    <attribute name="selectedIcon">1</attribute>
                    <inputs>
                        <dataPoint i="idp0000" full="false">
                            <value>0</value>
                        </dataPoint>
                        <dataPoint i="idp0001" full="false">
                            <value>0</value>
                        </dataPoint>
                        <dataPoint i="idp0002" full="false">
                            <value>0</value>
                        </dataPoint>
                        <dataPoint i="idp0003" full="false">
                            <value>0</value>
                        </dataPoint>
                        <dataPoint i="idp0004" full="false">
                            <value>1</value>
                        </dataPoint>
                    </inputs>
                    <outputs>
                        <dataPoint i="odp0000" full="false">
                            <value>0</value>
                        </dataPoint>
                        <dataPoint i="odp0001" full="false">
                            <value>0</value>
                        </dataPoint>
                    </outputs>
                    <parameters>
                        <parameter i="pm0000">
                            <value>60</value>
                        </parameter>
                        <parameter i="pm0001">
                            <value>1</value>
                        </parameter>
                        <parameter i="pm0007">
                            <value>1</value>
                        </parameter>
                    </parameters>
                    <scenes/>
                </channel>
            </channels>
        </device>
```

**Comment by ruebox** [comment]
The current implementation supports to send commands to the free@home devices. Feedback from f@h to the oh binding is currently not supported, yet what might be necessary to support the mentioned device.

I would assume that all sensors provide an UpdateEvent so that the functionality can be realized. I planned this mimic after the main deviceTypeIds are properly supported. 

Thanks for your patience.

**Comment by lassem** [comment]
The difference between #22 and #23 is that this one (900A) has a relay in it; that can be switched on or off.

**Comment by lassem** [comment]
This one http://installationmaterials.com/catalog/20267/Movement%20detector%2Fswitch%20actuator_ENG1.html
vs the one without a relay:
http://installationmaterials.com/catalog/20266/Movement%20detector_ENG1.html

**Comment by ruebox** [comment]
ah ok. Sounds reasonable. Can be done with the next update. Which might take little bit longer than one day ;-)

**Comment by ruebox** [comment]
would be great if you can check the devices on list it in the wiki. This will provide a good overview on the functionality ... thx

**Comment by lassem** [comment]
I am working my way through the wiki page 👍

**Comment by BastianZim** [comment]
@lassem Hey, short question. Where do you get that code from, cause I have a couple devices that I could provide as well, but I don’t know what I would have to do for that. 
Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lassem** [comment]
@Lucurus It is an excerpt from my `getAll.xml` file. This binding can drop the getAll.xml in the /tmp folder if you turn on debugging. Then it just a matter of searching for the correct serial number.
The serial number I just look for in the regular free@home web interface.

Does that help?

**Comment by BastianZim** [comment]
@lassem Yes, that helps immensely, thank you. 
I was aware of the getAll.xml but didn’t know where to look exactly, thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ruebox** [comment]
@lassem @Lucurus Just a short comment on the getAll.xml. It provides a good overview on the channels of the devices. However, I realized that only channels that provide a displayName
e.g. <attribute name="displayName">Lys i tak</attribute> work when addressed via XMPP.

Sensors such as hardware switches in the wall (and not the actors in the electrical distribution) can not be controlled via the SysAP WebUI and thus can not receive commands via XMPP. Those devices also do not send an update event to the WebUI (unfortunately). 

Please check if this is a true assumption. Might be that I am wrong.

**Comment by BastianZim** [comment]
@ruebox Just checked and yes, you're right, not sure what we can do here. I guess we would have to find out where those statuses are stored, but I don't know how to do that.
B+J allows you to download an error protocol, maybe that would be helpful in order to identify stuff?

**Comment by ruebox** [comment]
@Lucurus The binding currently relies on XMPP protocol. As these sensors commonly control the actors that can be controlled by openhab, I would propose to set it to a lower prio. Let us first finalize the stuff we know. Afterwards we can checkout further reverse engineering. What do you think?

**Comment by ruebox** [comment]
Accumulated issue #32 for sensor support -> Close this issue.

**Comment by BastianZim** [comment]
@ruebox Yes, sounds good. I think prio 1 should be "backtalking" of the things and investigate this at a later point.

**Comment by ruebox** [comment]
@Lucurus Backtalking draft implementation is ongoing ... not yet finalized.
