### ISSUE TITLE
free@home Wetterstation 6228

### ISSUE THREAD

**Issue by Salve87** [ruebox/openhab2-addons#28]
Hey Guys,
can I support with the integration of the weather station?
I'd love to have the Infos.

Best regards and thanks for the great work

**Comment by BastianZim** [comment]
Hey, @ruebox would have to weight in, but as far as I know, the binding does not yet support „talk-back“ from the devices so until that is implemented you might have to wait. 
But, if you want to do something in the meantime, it would be great if you could test all the devices you have and add them as _OK_ or _NOK_ in the wiki. 
If you need any help with that please do not hesitate to ask me!
Best.

**Comment by Salve87** [comment]
I edited the footer  of wiki :-) sorry I'm new to all of this

**Comment by BastianZim** [comment]
No problem, I’ll add it for you. Short question, when you go to the “Things”-Tab in OpenHab and click on the sensor, what number is in the name? It will probably be 100C, but I just want to double check. Also, do you have any other devices besides the weather station and the sensor that you could test?

**Comment by Salve87** [comment]
Not sure if the helps.

I habe the 7" Display to also control the BuschJäger Welcomehome Doorbell

![bildschirmfoto 2018-04-01 um 12 18 00](https://user-images.githubusercontent.com/37770456/38172132-db3c46ea-35a6-11e8-90e9-8a0f0514492e.png)

**Comment by BastianZim** [comment]
That should be fine, thanks. I'm not home right now, so I can only check it tomorrow but I'll come back to you on it!

**Comment by Salve87** [comment]
I have 5 Raffstore switches like to one above. In addition Openhab also found those Dummy Items:
Can I test any of them?  Help an support.

![bildschirmfoto 2018-04-01 um 12 30 47](https://user-images.githubusercontent.com/37770456/38172228-a50fc3ba-35a8-11e8-8b66-076a868ad243.png)

**Comment by BastianZim** [comment]
Thanks for the list, dummy items are items that aren't yet supported, so there is nothing yet that you can do, but I will add you to the list later as someone that can test it.
Thanks!

**Comment by BastianZim** [comment]
Hey, just to check, do you have the newest update for the binding? Because the DeviceID should be included in the name of the item, which isn't in your screenshot.

**Comment by Salve87** [comment]
Hey lucrus 
Just to check. A screenshot after adding the dummy to Things.

**Comment by Salve87** [comment]
It didn‘t upload the picture using the phone.
The Data:
Dummy_Wetterstation_Wetterstation_7EB1000005DA 
ONLINE
Dummy item
freeathome:dummy:7EB1000005DA

I Hope that helps. Would be great to have the Station running 
Thanks

**Comment by BastianZim** [comment]
Ok, your DeviceID is not included in the name, which I would need to add you to the wiki, but that is not too important, if you can't find it, that's fine as well.

The weather station can only be included once back talk is available as far as I know.

@ruebox Does this sound correct?

**Comment by Salve87** [comment]
Hello Lucurus and Ruebox,
Can you Tell me were i can find the deviceid? In the free@home gui? Ok is there a Link?
Can i support in any way to get back Talk available?
Thanks alot for you great work!

**Comment by ruebox** [comment]
@Salve87 sorry missed your message.

I am currently struggling with the update events that are working in my installation but not @the others. a working update mechanisms is necessary to properly integrate weather station.

I will you all know when update events are properly handled.

In the latest version the discovered items contain the device is. Just send the title string😉

**Comment by ruebox** [comment]
@Salve87 I got the update mechanism up and running please refer to #11.

There you will also find a recent snapshot that traces the update events if debug logging is enabled.
The events are traces in update.csv. so if you provide me the update.csv incl. A description on the meaning, it should be feasible to support weather station. 

If you enable discovery of dummy things, thevrequired  device type id will be encoded in the name.

**Comment by Salve87** [comment]
Hello Ruebox,
I Installed the new snapshot (03.05.2018). Unfortunately I can't find update.csv File. Can somebody help? I'm using a Raspberry Pi.

I Now have the device Type id shown.

![bildschirmfoto 2018-05-08 um 22 28 17](https://user-images.githubusercontent.com/37770456/39781341-36a349e0-530f-11e8-8368-e58d3ecab4b0.png)

**Comment by ruebox** [comment]
Hi
Please activate debugging logging in the config of the bridge.

Please note that sometimes the xml can not be properly fetched. Thus I would propose that you completely delete the bridge and restart it with new config.

Then the update events should be logged.

**Comment by ruebox** [comment]
@Salve87 did you get it run?

**Comment by Salve87** [comment]
Hey Ruebox,
Sorry was away the last days.
I tried to get the log file running. I installed the binding and the free at home bridge like 20 times.
I can't find any Logfile in the Openhabian Dir. 
As I understand there should be a folder/file in "openHAB-share/openhab2-userdata/tmp"
Or am I wrong?
I guess I need support again. 

Thanks Salve


![bildschirmfoto 2018-05-13 um 21 17 20](https://user-images.githubusercontent.com/37770456/39970874-194787c0-56f3-11e8-93c5-88a937657021.png)

**Comment by Salve87** [comment]
Hey Guys, any idea what i could do?
I could offer TeamViewer?

**Comment by ruebox** [comment]
Hi sorry for being late.

We should check if the weather station send update events. 
What's displayed if you open the weather station in the official web UI of bj . Do you see latest data such as wind, temperature etc? Are the values updated?

**Comment by ruebox** [comment]
The update events via xmpp can be tracked via the firefox network manager https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

Are there new update events from weather station?

**Comment by ruebox** [comment]
Do you use latest snapshot #40

**Comment by Salve87** [comment]
Hey Ruebox
i made a screenshots,
the data is updated every sec.
See the screenshot:

![bildschirmfoto 2018-05-19 um 22 30 13](https://user-images.githubusercontent.com/37770456/40272831-a35a4d56-5bb4-11e8-96cd-8db2809e2a64.png)

**Comment by ruebox** [comment]
Hi
This looks like xmpp messages and not update events as with the other devices.

Can you send me an exported excerpt of these events.
Do you have an idea how the data is encoded? Which information is displayed?

**Comment by Salve87** [comment]
Hello Ruebox,
I found the temperature (20,8) and Lux (24719.4) updates.
After exporting it looked like that:
Didn't find the wind yet, since its bin 0, the last days.
Is that useful?






        "serverIPAddress": "192.168.187.5",
        "connection": "5280"
      },
      {
        "pageref": "page_3",
        "startedDateTime": "2018-05-20T16:39:03.079+02:00",
        "time": null,
        "request": {
          "bodySize": 154,
          "method": "POST",
          "url": "http://192.168.187.5:5280/http-bind",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "192.168.187.5:5280"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "de,en-US;q=0.7,en;q=0.3"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Referer",
              "value": "http://192.168.187.5/"
            },
            {
              "name": "Content-Type",
              "value": "text/xml; charset=utf-8"
            },
            {
              "name": "Content-Length",
              "value": "154"
            },
            {
              "name": "Origin",
              "value": "http://192.168.187.5"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [],
          "queryString": [],
          "postData": {
            "mimeType": "text/xml; charset=utf-8",
            "params": [],
            "text": "<body rid='886339' sid='e409ecce-2b10-4c86-aa15-cbb48bf06e06' xmlns='http://jabber.org/protocol/httpbind' key='37634a1f35c5837a0c72359f07c5bb1a0c1cea37'/>"
          },
          "headersSize": 383
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Access-Control-Max-Age",
              "value": "7200"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "GET, POST, OPTIONS"
            },
            {
              "name": "access-control-allow-headers",
              "value": "Content-Type"
            },
            {
              "name": "Content-Length",
              "value": "1388"
            },
            {
              "name": "Access-Control-Allow-Origin",
              "value": "*"
            },
            {
              "name": "Content-Type",
              "value": "text/xml; charset=utf-8"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/xml; charset=utf-8",
            "size": 1388,
            "text": "<body sid='e409ecce-2b10-4c86-aa15-cbb48bf06e06' xmlns:stream='http://etherx.jabber.org/streams' xmlns='http://jabber.org/protocol/httpbind'><message xmlns='jabber:client' type='headline' to='installer@busch-jaeger.de/5754c8' from='mrha@busch-jaeger.de'><event xmlns='http://jabber.org/protocol/pubsub#event'><items node='http://abb.com/protocol/update'><item id='1'><update xmlns='http://abb.com/protocol/update'><data>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;project timeStamp=&quot;5568792&quot; sessionId=&quot;2cf5d74a&quot; type=&quot;update&quot; mrhaVersion=&quot;2.1.7&quot; mrhaBuild=&quot;5969&quot;&gt;&lt;privileges/&gt;&lt;devices&gt;&lt;device individualAddress=&quot;0166&quot; profile=&quot;0E00&quot; serialNumber=&quot;7EB1000005DA&quot; domainAddress=&quot;005D&quot; state=&quot;modified&quot; commissioningState=&quot;ready&quot; progress=&quot;100&quot;&gt;&lt;channels&gt;&lt;channel state=&quot;modified&quot; i=&quot;ch0000&quot; cid=&quot;7EB10382&quot;&gt;&lt;inputs/&gt;&lt;outputs&gt;&lt;dataPoint state=&quot;modified&quot; i=&quot;odp0001&quot; full=&quot;false&quot;&gt;&lt;value&gt;24719.4&lt;/value&gt;&lt;/dataPoint&gt;&lt;/outputs&gt;&lt;parameters/&gt;&lt;scenes/&gt;&lt;/channel&gt;&lt;/channels&gt;&lt;parameters/&gt;&lt;/device&gt;&lt;/devices&gt;&lt;/project&gt;\n</data></update></item></items></event></message></body>"
          },
          "redirectURL": "",
          "headersSize": 236,
          "bodySize": 1388
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "send": 0,
          "wait": 28,
          "receive": 0
        },






        "serverIPAddress": "192.168.187.5",
        "connection": "5280"
      },
      {
        "pageref": "page_3",
        "startedDateTime": "2018-05-20T16:39:03.257+02:00",
        "time": null,
        "request": {
          "bodySize": 154,
          "method": "POST",
          "url": "http://192.168.187.5:5280/http-bind",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "192.168.187.5:5280"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "de,en-US;q=0.7,en;q=0.3"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Referer",
              "value": "http://192.168.187.5/"
            },
            {
              "name": "Content-Type",
              "value": "text/xml; charset=utf-8"
            },
            {
              "name": "Content-Length",
              "value": "154"
            },
            {
              "name": "Origin",
              "value": "http://192.168.187.5"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [],
          "queryString": [],
          "postData": {
            "mimeType": "text/xml; charset=utf-8",
            "params": [],
            "text": "<body rid='886340' sid='e409ecce-2b10-4c86-aa15-cbb48bf06e06' xmlns='http://jabber.org/protocol/httpbind' key='f037ac3513b56fa28a39fe44a1ee730a37f2122f'/>"
          },
          "headersSize": 383
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Access-Control-Max-Age",
              "value": "7200"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "GET, POST, OPTIONS"
            },
            {
              "name": "access-control-allow-headers",
              "value": "Content-Type"
            },
            {
              "name": "Content-Length",
              "value": "1386"
            },
            {
              "name": "Access-Control-Allow-Origin",
              "value": "*"
            },
            {
              "name": "Content-Type",
              "value": "text/xml; charset=utf-8"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/xml; charset=utf-8",
            "size": 1386,
            "text": "<body sid='e409ecce-2b10-4c86-aa15-cbb48bf06e06' xmlns:stream='http://etherx.jabber.org/streams' xmlns='http://jabber.org/protocol/httpbind'><message xmlns='jabber:client' type='headline' to='installer@busch-jaeger.de/5754c8' from='mrha@busch-jaeger.de'><event xmlns='http://jabber.org/protocol/pubsub#event'><items node='http://abb.com/protocol/update'><item id='1'><update xmlns='http://abb.com/protocol/update'><data>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;project timeStamp=&quot;5568793&quot; sessionId=&quot;2cf5d74a&quot; type=&quot;update&quot; mrhaVersion=&quot;2.1.7&quot; mrhaBuild=&quot;5969&quot;&gt;&lt;privileges/&gt;&lt;devices&gt;&lt;device individualAddress=&quot;0166&quot; profile=&quot;0E00&quot; serialNumber=&quot;7EB1000005DA&quot; domainAddress=&quot;005D&quot; state=&quot;modified&quot; commissioningState=&quot;ready&quot; progress=&quot;100&quot;&gt;&lt;channels&gt;&lt;channel state=&quot;modified&quot; i=&quot;ch0002&quot; cid=&quot;7EB103C1&quot;&gt;&lt;inputs/&gt;&lt;outputs&gt;&lt;dataPoint state=&quot;modified&quot; i=&quot;odp0001&quot; full=&quot;false&quot;&gt;&lt;value&gt;20.08&lt;/value&gt;&lt;/dataPoint&gt;&lt;/outputs&gt;&lt;parameters/&gt;&lt;scenes/&gt;&lt;/channel&gt;&lt;/channels&gt;&lt;parameters/&gt;&lt;/device&gt;&lt;/devices&gt;&lt;/project&gt;\n</data></update></item></items></event></message></body>"
          },
          "redirectURL": "",
          "headersSize": 236,
          "bodySize": 1386
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "send": 0,
          "wait": 479,
          "receive": 0
        },

**Comment by Salve87** [comment]
Can you contact me? I could give you access to my Pc via Teamviewer

**Comment by ruebox** [comment]
Hi,
Based on the xml excerpt I can introduce the weather station. When you can also provide the xml for wind Iwould add the following channels
* Wind
* Temperature
* Illumination

Let me see when I can provide a snapshot.

**Comment by ruebox** [comment]
Update events for weather station with deviceTypeID **101D**:

1. **Illumination (lux)**: ch0000/opd0001
```xml
<body sid='e409ecce-2b10-4c86-aa15-cbb48bf06e06' xmlns:stream='http://etherx.jabber.org/streams' xmlns='http://jabber.org/protocol/httpbind'>
<message xmlns='jabber:client' type='headline' to='installer@busch-jaeger.de/5754c8' from='mrha@busch-jaeger.de'>
<event xmlns='http://jabber.org/protocol/pubsub#event'>
<items node='http://abb.com/protocol/update'><item id='1'>
<update xmlns='http://abb.com/protocol/update'><data>
<?xml version="1.0" encoding="UTF-8"?>
<project timeStamp="5568792" sessionId="2cf5d74a" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device individualAddress="0166" profile="0E00" serialNumber="7EB1000005DA" domainAddress="005D" state="modified" commissioningState="ready" progress="100">
<channels>
<channel state="modified" i="ch0000" cid="7EB10382">
<inputs/>
<outputs>
<dataPoint state="modified" i="odp0001" full="false"><value>24719.4</value></dataPoint>
</outputs>
<parameters/>
<scenes/></channel></channels><parameters/></device></devices></project>\n</data></update></item></items></event></message></body>
```
2. **Wind (m/s):** ch0003/odp0003
```xml
<?xml version="1.0" encoding="UTF-8"?><project timeStamp="5619485" sessionId="2cf5d74a" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices>
<device individualAddress="0166" profile="0E00" serialNumber="7EB1000005DA" domainAddress="005D" state="modified" commissioningState="ready" progress="100">
<channels>
<channel state="modified" i="ch0003" cid="7EB103E1"><inputs/><outputs>
<dataPoint state="modified" i="odp0003" full="false">
<value>1.95</value></dataPoint></outputs><parameters/><scenes/></channel></channels><parameters/></device></devices></project>
```
3.  **Temperature (°C)**: ch0002/opd0001
```xml
<data>
<?xml version="1.0" encoding="UTF-8"?>
<project timeStamp="5568793" sessionId="2cf5d74a" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices><device individualAddress="0166" profile="0E00" serialNumber="7EB1000005DA" domainAddress="005D" state="modified" commissioningState="ready" progress="100">
<channels>
<channel state="modified" i="ch0002" cid="7EB103C1"><inputs/><outputs>
<dataPoint state="modified" i="odp0001" full="false"><value>20.08</value></dataPoint>
</outputs><parameters/><scenes/></channel></channels><parameters/></device></devices></project>\n</data></update></item></items></event></message></body>
```


4. **Rain on/off:** **ch0001/odp0000
```xml
<?xml version="1.0" encoding="UTF-8"?><project timeStamp="5622368" sessionId="2cf5d74a" type="update" mrhaVersion="2.1.7" mrhaBuild="5969"><privileges/><devices>
<device individualAddress="0166" profile="0E00" serialNumber="7EB1000005DA" domainAddress="005D" state="modified" commissioningState="ready" progress="100">
<channels>
<channel state="modified" i="ch0001" cid="7EB103A2"><inputs/><outputs>
<dataPoint state="modified" i="odp0000" full="false">
<value>1</value>
</dataPoint></outputs><parameters/><scenes/></channel></channels><parameters/></device></devices></project>
```

**Comment by Salve87** [comment]
Hello Ruebox
I used my water hose to simulate some rain and wind. :-)
I found 4 Channels. 

Illumination on ch0000 value: 61890.6
Wind on ch0003 value: 1.95m/s
Temp: ch0002 value: 15.93
Rain: ch0001 value:1 (the station only shows rain:yes/no; I guess yes=1/no=0)

</message></log></item></items></event></message><message xmlns='jabber:client' type='headline' to='installer@busch-jaeger.de/64fae3' from='mrha@busch-jaeger.de'><event xmlns='http://jabber.org/protocol/pubsub#event'><items node='http://abb.com/protocol/update'><item id='1'><update xmlns='http://abb.com/protocol/update'><data>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;project timeStamp=&quot;5619483&quot; sessionId=&quot;2cf5d74a&quot; type=&quot;update&quot; mrhaVersion=&quot;2.1.7&quot; mrhaBuild=&quot;5969&quot;&gt;&lt;privileges/&gt;&lt;devices&gt;&lt;device individualAddress=&quot;0166&quot; profile=&quot;0E00&quot; serialNumber=&quot;7EB1000005DA&quot; domainAddress=&quot;005D&quot; state=&quot;modified&quot; commissioningState=&quot;ready&quot; progress=&quot;100&quot;&gt;&lt;channels&gt;&lt;channel state=&quot;modified&quot; i=&quot;ch0000&quot; cid=&quot;7EB10382&quot;&gt;&lt;inputs/&gt;&lt;outputs&gt;&lt;dataPoint state=&quot;modified&quot; i=&quot;odp0001&quot; full=&quot;false&quot;&gt;&lt;value&gt;61890.6&lt;/value&gt;&lt;/dataPoint&gt;&lt;/outputs&gt;&lt;parameters/&gt;&lt;scenes/&gt;&lt;/channel&gt;&lt;/channels&gt;&lt;parameters/&gt;&lt;/device&gt;&lt;/devices&gt;&lt;/project&gt;

</data></update></item></items></event></message><message xmlns='jabber:client' type='headline' to='installer@busch-jaeger.de/64fae3' from='mrha@busch-jaeger.de'><event xmlns='http://jabber.org/protocol/pubsub#event'><items node='http://abb.com/protocol/update'><item id='1'><update xmlns='http://abb.com/protocol/update'><data>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;project timeStamp=&quot;5619484&quot; sessionId=&quot;2cf5d74a&quot; type=&quot;update&quot; mrhaVersion=&quot;2.1.7&quot; mrhaBuild=&quot;5969&quot;&gt;&lt;privileges/&gt;&lt;devices&gt;&lt;device individualAddress=&quot;0166&quot; profile=&quot;0E00&quot; serialNumber=&quot;7EB1000005DA&quot; domainAddress=&quot;005D&quot; state=&quot;modified&quot; commissioningState=&quot;ready&quot; progress=&quot;100&quot;&gt;&lt;channels&gt;&lt;channel state=&quot;modified&quot; i=&quot;ch0002&quot; cid=&quot;7EB103C1&quot;&gt;&lt;inputs/&gt;&lt;outputs&gt;&lt;dataPoint state=&quot;modified&quot; i=&quot;odp0001&quot; full=&quot;false&quot;&gt;&lt;value&gt;15.93&lt;/value&gt;&lt;/dataPoint&gt;&lt;/outputs&gt;&lt;parameters/&gt;&lt;scenes/&gt;&lt;/channel&gt;&lt;/channels&gt;&lt;parameters/&gt;&lt;/device&gt;&lt;/devices&gt;&lt;/project&gt;

</data></update></item></items></event></message><message xmlns='jabber:client' type='headline' to='installer@busch-jaeger.de/64fae3' from='mrha@busch-jaeger.de'><event xmlns='http://jabber.org/protocol/pubsub#event'><items node='http://abb.com/protocol/update'><item id='1'><update xmlns='http://abb.com/protocol/update'><data>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;project timeStamp=&quot;5619485&quot; sessionId=&quot;2cf5d74a&quot; type=&quot;update&quot; mrhaVersion=&quot;2.1.7&quot; mrhaBuild=&quot;5969&quot;&gt;&lt;privileges/&gt;&lt;devices&gt;&lt;device individualAddress=&quot;0166&quot; profile=&quot;0E00&quot; serialNumber=&quot;7EB1000005DA&quot; domainAddress=&quot;005D&quot; state=&quot;modified&quot; commissioningState=&quot;ready&quot; progress=&quot;100&quot;&gt;&lt;channels&gt;&lt;channel state=&quot;modified&quot; i=&quot;ch0003&quot; cid=&quot;7EB103E1&quot;&gt;&lt;inputs/&gt;&lt;outputs&gt;&lt;dataPoint state=&quot;modified&quot; i=&quot;odp0003&quot; full=&quot;false&quot;&gt;&lt;value&gt;1.95&lt;/value&gt;&lt;/dataPoint&gt;&lt;/outputs&gt;&lt;parameters/&gt;&lt;scenes/&gt;&lt;/channel&gt;&lt;/channels&gt;&lt;parameters/&gt;&lt;/device&gt;&lt;/devices&gt;&lt;/project&gt;

</message></log></item></items></event></message><message xmlns='jabber:client' type='headline' to='installer@busch-jaeger.de/64fae3' from='mrha@busch-jaeger.de'><event xmlns='http://jabber.org/protocol/pubsub#event'><items node='http://abb.com/protocol/update'><item id='1'><update xmlns='http://abb.com/protocol/update'><data>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;project timeStamp=&quot;5622368&quot; sessionId=&quot;2cf5d74a&quot; type=&quot;update&quot; mrhaVersion=&quot;2.1.7&quot; mrhaBuild=&quot;5969&quot;&gt;&lt;privileges/&gt;&lt;devices&gt;&lt;device individualAddress=&quot;0166&quot; profile=&quot;0E00&quot; serialNumber=&quot;7EB1000005DA&quot; domainAddress=&quot;005D&quot; state=&quot;modified&quot; commissioningState=&quot;ready&quot; progress=&quot;100&quot;&gt;&lt;channels&gt;&lt;channel state=&quot;modified&quot; i=&quot;ch0001&quot; cid=&quot;7EB103A2&quot;&gt;&lt;inputs/&gt;&lt;outputs&gt;&lt;dataPoint state=&quot;modified&quot; i=&quot;odp0000&quot; full=&quot;false&quot;&gt;&lt;value&gt;1&lt;/value&gt;&lt;/dataPoint&gt;&lt;/outputs&gt;&lt;parameters/&gt;&lt;scenes/&gt;&lt;/channel&gt;&lt;/channels&gt;&lt;parameters/&gt;&lt;/device&gt;&lt;/devices&gt;&lt;/project&gt;

**Comment by Salve87** [comment]
@ruebox:
Do you need more information?

**Comment by ruebox** [comment]
great ... just about to implement a first prototype of the weather station ... would say in 15 minutes ... first is ready for testing

**Comment by ruebox** [comment]
Please find a prototype **snapshot** implementation of the weather station. Rain on/off is not supported, yet, but temperature, wind, illumination.

Please let me know what is working and what not ;-) unfortunately I can not test it myself.

[org.openhab.binding.freeathome-2.0.0-SNAPSHOT.jar.weather.210518.zip](https://github.com/ruebox/openhab2-addons/files/2021787/org.openhab.binding.freeathome-2.0.0-SNAPSHOT.jar.weather.210518.zip)

**Comment by Salve87** [comment]
ok testing

**Comment by Salve87** [comment]
Hey Ruebox, 
sorry for taking so much time. (after restarting the Raspberry, it didn't show up anymore. --> problem solved after several restarts.)

The weather station is running great !!!
![bildschirmfoto 2018-05-21 um 13 30 16](https://user-images.githubusercontent.com/37770456/40305615-8833d720-5cfb-11e8-9ec9-ceee0175de14.png)

Could you check for the rain yes/no function and for wind the digit after the comma is always 0
Thank you so much for the great work.

**Comment by ruebox** [comment]
Great good to know 😁😀
Just recognized that wind m/s comes with ch0003/odp0003 and not odp0001. Odp0001 could be bft.

Does this sound reasonable?

Rain on/off no big deal.

**Comment by ruebox** [comment]
Please find a new snapshot weather-2 supporting
- wind (m/s): channels updated
- Rain: on/off

Please remove old weather station things as the configuration changed and let me know if it is working :-)
[org.openhab.binding.freeathome-2.0.0-SNAPSHOT.jar.weather-2.210518.zip](https://github.com/ruebox/openhab2-addons/files/2022885/org.openhab.binding.freeathome-2.0.0-SNAPSHOT.jar.weather-2.210518.zip)

**Comment by Salve87** [comment]
Both is now working perfectly, Thank you so much
