### ISSUE TITLE
Should Hue be integrated?

### ISSUE THREAD

**Issue by BastianZim** [ruebox/openhab2-addons#30]
Hey, I just wanted to ask, if we should integrate hue actors as well since OpenHAB already offers a binding for it?
If yes I would start testing them as well, but I just wasn't sure if we really need it.

Best

**Comment by TheSpirit** [comment]
I thing this is not needed.

**Comment by Salve87** [comment]
I have it integrated via the Hue Binding. Works perfectly for me

**Comment by lassem** [comment]
The state of the bulb is reflected in the OpenHAB UI correctly I assume? If you turn it on and off using a Free@Home switch I mean.

**Comment by BastianZim** [comment]
Yes, I think so, what I meant is, since you can control Hue lights via B+J it would be possible to control them via OpenHab and this binding: _OpenHAB -> B+J Binding -> B+J SysAP -> Hue Bridge -> Hue light_ and I’m not sure if it’s necessary to add them to this binding, since it is possible to control them from OpenHAB directly via the Hue binding: _OpenHAB -> Hue Binding -> Hue Bridge -> Hue light_. 

It is possible to implement it and some things are already supported, I think, but I just wanted to get the general interest in this because I think it’s unnecessary to support them as well through this binding, that would just be more work but if everybody else wants this I would start to get the necessary files.

**Comment by ruebox** [comment]
@Lucurus  The Hue switch actor with deviceId: 10C4 is supported with channelID: ch0000
This is currently the only Hue device. 

I would assume that the device has to be reachable via SysAP WebUI.
Best

```

 // // Hue Schaltaktor
                    case "10C4": {
                        String channelId = "ch0000";
                        ThingUID uid = new ThingUID(FreeAtHomeBindingConstants.SWITCH_THING_TYPEUID,
                                device.Serial + "_" + channelId);
                        Map<String, Object> properties = new HashMap<>(1);
                        properties.put("deviceId", device.Serial);
                        properties.put("channelId", channelId);

                        DiscoveryResult discoveryResult = DiscoveryResultBuilder.create(uid)
                                .withLabel(device.DeviceDisplayName + "_" + device.DeviceTypeName + "_" + deviceTypeId
                                        + "_" + device.Serial + "_" + channelId)
                                .withBridge(bridgeUID).withProperties(properties).build();
thingDiscovered(discoveryResult);
```

**Comment by BastianZim** [comment]
@ruebox Yes, I was just wondering if we should continue to support it. If yes, I can provide other devices and their data as well, but as laid out, I don't think we should since there is already a binding.

**Comment by ruebox** [comment]
Closed as not devices can be used via openhab hue binding. @Lucurus If not, please let me know
