### ISSUE TITLE
next snapshot release date?

### ISSUE THREAD

**Issue by TheSpirit** [ruebox/openhab2-addons#31]
Hi.
When will we see the next snapshot release?
Would like to test.
Best regards,
Andreas

**Comment by ruebox** [comment]
Plan to provide an update end of the week. If talkback will be available I have to see.

**Comment by TheSpirit** [comment]
looking forward to it

**Comment by ruebox** [comment]
Hi, planned for tomorrow evening. Just no time for pushing it faster ...

**Comment by TheSpirit** [comment]
sounds great; ready for testing

**Comment by ruebox** [comment]
new snapshot available #35
