### ISSUE TITLE
Raffstore dosent work

### ISSUE THREAD

**Issue by sascha-wojewsky-IPD** [ruebox/openhab2-addons#38]
Hi,

first of all, thank you a lot for your work!
I've a raspian pi 3 with openhabian and the latest version of your freeathome bindings.
I've a problem with my raffstores. Openhab found everything but nothing happend..

I've got:
2018-05-04 13:06:05.069 [INFO ] [e.handler.FreeAtHomeRaffStoreHandler] - Called channel STEPWISE: ABB700CF59A3/ch0000/idp0001

2018-05-04 13:06:05.170 [INFO ] [home.handler.FreeAtHomeBridgeHandler] - Received IQ: Inbound IQ-result (9cf78952-8f5b-4b6b-9bae-ca3273a167cc) from 'mrha@busch-jaeger.de/rpc' to '05a83934-2cb2-4c9d-8ce1-ed2da78fcd08@busch-jaeger.de/8a2b63f4-0bbf-461a-bb4a-772fc6fd4808'

Extension(s):

Response: true

2018-05-04 13:06:59.408 [INFO ] [home.handler.FreeAtHomeBridgeHandler] - Received: Headline Message from 'mrha@busch-jaeger.de' to '05a83934-2cb2-4c9d-8ce1-ed2da78fcd08@busch-jaeger.de/8a2b63f4-0bbf-461a-bb4a-772fc6fd4808'

Extension(s):

rocks.xmpp.extensions.pubsub.model.event.Event@f70d44

Could you give me a hint?

Groups are working. Just all single Raffstore didn't work

**Comment by ruebox** [comment]
Hi 
The raffstores work quite stable ... The only I can imagine is that you might have an outdated firmware ...

**Comment by sascha-wojewsky-IPD** [comment]
I've the latest free@home Version. 2.17

**Comment by ruebox** [comment]
Can you control the raffstore via the webui of freeathome?
Could you please check if the serial number of the device fits to the raffstore configuration?

Which actor do you have? Is it recognized by discovery?

Which binding snapshot are you using

**Comment by sascha-wojewsky-IPD** [comment]
I can control all raffstores with the webui, groups and also each single actor.

In openhab i've used the discovery Funktion. How do i check the serials of the actor?

Thank you a lot for your help

**Comment by ruebox** [comment]
Some people reported that only devices can be controlled that are visible in the floor plan. I will provide some more info this evening best

**Comment by ruebox** [comment]
@TheSpirit didn't you also have some trouble with your raffstores ... Do you perhaps have a hint

**Comment by TheSpirit** [comment]
for me it works just fine now after using the latest build.
maybe it is a new device with another id or other idp or odp number.
maybe he can provide the update.csv and the getall.xml file

**Comment by sascha-wojewsky-IPD** [comment]
Sorry, but im absolutly new in openhab... Where can I find these files?

I've tried the raffstore items several times. After this I've got an error in the free@home webfrontend. 
I'll try today to reproduce it an will post the error message

**Comment by sascha-wojewsky-IPD** [comment]
Now ive found the new Version (2018.05.04) and Now everything is working.

Thank you a lot

**Comment by ruebox** [comment]
Great good to know.
