### ISSUE TITLE
Sensor/ Jalousieaktor 1/1

### ISSUE THREAD

**Issue by Salve87** [ruebox/openhab2-addons#41]
Hello Guys, 
I noticed, that the Sensor/ Jalousieaktor 1/1 randomly looses the position of the raffstores.
Also the shutter complete and stepwise function doesn't work. 
I use the percentage function, to move the raffstores.

Sensor/ Jalousieaktor 1/1-fach_Sensor/ Jalousieaktor 1/1-fach_1013_ABB700D02ABE_ch0003

**PaperUI**
![bildschirmfoto 2018-06-08 um 15 05 04](https://user-images.githubusercontent.com/37770456/41159870-440e942c-6b2e-11e8-9d60-be05077ace3f.png)

**HabPanel**
![bildschirmfoto 2018-06-08 um 15 12 13](https://user-images.githubusercontent.com/37770456/41160217-3ff0ee0c-6b2f-11e8-8b54-c2188c5834cc.png)

Would be great if you could solve the problem. 

Greets

**Comment by ruebox** [comment]
Could you please send me the logs otherwise it is difficult to analyse

**Comment by Salve87** [comment]
Hey Ruebox, 
sorry took some time: here the Log files for opening/closing complete, stepwise and to a percentage:

**Opening**

`ABB700CC4353&quot;domainAddress=&quot;005D&quot; state=&quot;modified&quot; commissioningState=&quot;ready&quot; progress=&quot;100&quot;&gt;&lt;channels&gt;&lt;channel state=&quot;modified&quot; i=&quot;ch0003&quot; cid=&quot;`
complete:
`ABB700CC4353/ch0003/idp0000</string></value></param><param><value><string>0</string></value></param></params></methodCall></query></iq></body>"`
Stepwise:
`ABB700CC4353/ch0003/idp0001</string></value></param><param><value><string>0</string></value></param></params></methodCall></query></iq></body>"`
opening to 45%:
`ABB700CC4353/ch0003/idp0002</string></value></param><param><value><string>45</string></value></param></params></methodCall></query></iq></body>"`

**closing** 
`ABB700CC4353&quot; domainAddress=&quot;005D&quot; state=&quot;modified&quot; commissioningState=&quot;ready&quot; progress=&quot;100&quot;&gt;&lt;channels&gt;&lt;channel state=&quot;modified&quot; i=&quot;ch0003&quot; cid=&quot;`
complete
`ABB700CC4353/ch0003/idp0000</string></value></param><param><value><string>1</string></value></param></params></methodCall></query></iq></body>"`
Stepwise
`ABB700CC4353/ch0003/idp0001</string></value></param><param><value><string>1</string></value></param></params></methodCall></query></iq></body>"`
closing to 70%
`ABB700CC4353/ch0003/idp0002</string></value></param><param><value><string>70</string></value></param></params></methodCall></query></iq></body>"`

**For the other Problem:**
I have a few "programms/rules" running on the Free@home box. 
I think openhab looses the position of the raffstores as soon free@home changes the position (not trigger by OH2)

Hope that helps

**Comment by ruebox** [comment]
Hi thanks for the feedback.

What happens on paperui on the percentage if you press the physical switch?

Can you please send me the logs if this?

Which oh version do you use? I tested 2.2. thx

**Comment by ruebox** [comment]
@Salve87 do you have an update. Is it now working? What happens if the percentage is changed by physical switch?

**Comment by Salve87** [comment]
Sorry Guys for the late reply. My SD-Card broke and I didn't save anything.
Im about to setup everything again

**Comment by ruebox** [comment]
No reaction -> close
