### ISSUE TITLE
installed alpha version - no more connection to bridge

### ISSUE THREAD

**Issue by TheSpirit** [ruebox/openhab2-addons#42]
Today I removed my manual installation and installed the alpha version from marketplace.
after manually adding the bridge I get the following error

![bildschirmfoto 2018-07-05 um 20 18 09](https://user-images.githubusercontent.com/6056918/42340536-969a036c-8090-11e8-86d6-b6e28e979c42.png)

for info:
I Connect via another api to the bridge also.
Could this be a problem?
Thanks

**Comment by TheSpirit** [comment]
did a new try and now I get this:
![bildschirmfoto 2018-07-05 um 20 27 06](https://user-images.githubusercontent.com/6056918/42340993-dbe6e16e-8091-11e8-87bd-4700d6c27989.png)

**Comment by ruebox** [comment]
Did you completely remove the bridge and added a new instance?

The error remarks that the xmpp server is not reachable. Can you ping the sysap from raspi/openhab?

I also installed the version via marketplace and have a proper connection since a week.

**Comment by TheSpirit** [comment]
Hi.
It just works again.
Took longer than i was used to, to get the "online" sign.
