### ISSUE TITLE
blind can not be controlled / new case id´s

### ISSUE THREAD

**Issue by TheSpirit** [ruebox/openhab2-addons#9]
i just installed openhab and your binding.
my bridge is online and my blinds are found.
but how can i "move" the blinds via openhab?
i bound an item to the thing raffstore switch at first i tried the "shutter stepwise" and then the "shutter complete".
the blinds are these:
http://www.busch-jaeger-katalog.de/6220-0-0017,artikel.html
but the blind does not move.
thanks a lot

**Comment by TheSpirit** [comment]
i did some research within the xml file.
i think i found out some new "cases" how you call it within your discovery procedure:
my item R2 is programmed as a blind (rollo in german) and has the case number 61
item R3 is programmed as a shade (jalousie in german) and has the case number 9
the case number 3 is always the switch on top of my device.
attached find the getall xml.
what i also found out is, that for R2:
channel 3 -> odp0001 shows the actual position of the blind as a value of percentage.
maybe you can control the item via this value.
could you make a test device or how can i test this by myself.

[getAll.zip](https://github.com/ruebox/openhab2-addons/files/1842479/getAll.zip)

**Comment by ruebox** [comment]
Hi,
I implemented the blinds according to [sstadlberger](https://github.com/sstadlberger/home/blob/master/lib/freeathome/sysap-external.js). I do not have blinds with deviceId='1013' // Sensor/ Jalousieaktor 1/1-fach Thus, I can not test it.

What we could do is the following:
* Got to your freeathome SysAP webpage with firefox
* Open the menu "Web Developer" -> Network (Hot key: Ctrl-Shift-E)
* Reload
* Login to SysAP
* Bin: Clear all entries (to skip login logs)
* Go to the control of your blinds
* Move up and down
* WebDeveloperWindow: Right-click one log entry -> Save All as HAR
* Upload HAR and a description what you did to github.
* Screenshot of the device control would be great :-)

I would then check, which commands are transfer to SysAP.

Thx.

**Comment by TheSpirit** [comment]
save all as HAR does not do anything. do i have to wait very long? waited for about 5 min.
and  two questions to your programm:
what do you mean with "Bin: Clear all entries (to skip login logs)" how can i do this?
from wich page do you want to have a screenshot?

**Comment by TheSpirit** [comment]
i just had a look at sstadlberger and saw that the device id 1013 has been implemented.
maybe you can give me a hint how to configure it to work with your openhab implementation.
attached please find the har file.
[Archive 18-03-24 12-58-00.zip](https://github.com/ruebox/openhab2-addons/files/1844346/Archive.18-03-24.12-58-00.zip)
procedure:
1. pressed the down button within the blind window to start moving down
2. pressed the down button within the blind window to stop moving down
3. pressed the up button within the blind window to start moving up
4. pressed the up button within the blind window to stop moving up

**Comment by TheSpirit** [comment]
i did some research and now i can control the blind within openhab.
i can move up, down and stop the blind, but only via the buttons. 
it would be great to use the percentage value, because this is the only item i can use within my other home-system.
i had to use:
ch0003 and idp0000 and idp0001 as setting.
![working](https://user-images.githubusercontent.com/6056918/37863935-2a783d2c-2f67-11e8-90b9-f00a3171940c.PNG)

**Comment by ruebox** [comment]
Hi,
thanks a lot for the trace. I check it and found the following:
`<methodName>RemoteInterface.setDatapoint</methodName><params><param><value><string>**ABB700C9CE93/ch0003/idp0001**</string></value></param><param><value><string>1</string></value>`
What do I conclude from this:
* Your DeviceId = ABB700C9CE93
* The device does not only have 1 channel, but >= 4 with e.g. ch0003: How many channels does your device have? 4 or 8?

1. I implemented deviceID=1013 as a single channel device. If you acknowledge that it has 4 channels, I would change this in the code.
1. Just saw that it is working with channel ch0003

**Comment by TheSpirit** [comment]
the device has 4 channels like you could see within the getAll.xml
could you implement using the percentage value from openhab for controlling the blind?
i also saw this from sstadlberger:
`'shutter' : {
			'actions' : {
				'up' : { 'idp0000' : 0 },
				'down' : { 'idp0000' : 1 },
				'toggle-up' : { 'idp0000' : 'x-0' },
				'toggle-down' : { 'idp0000' : 'x-1' },
				'pulse-up' : { 'idp0000' : 'p-0' },
				'pulse-down' : { 'idp0000' : 'p-1' },
				'stop' : { 'idp0001' : 1 }
			},
			'deviceIds' : [
				'B001', // Jalousieaktor 4-fach, REG
				'1013' // Sensor/ Jalousieaktor 1/1-fach
			]
		},`

**Comment by ruebox** [comment]
Feed information from F@h back to openhab is the next step.

With the next build, the discovery with automatically set to channel ch0003. Thx

**Comment by TheSpirit** [comment]
the feedback is very important for me, because my main system is loxone.
and loxone controls the openhub blind only via the percentage value.
looking forward.
if there is anything else i can help you feel free to ask.

**Comment by ruebox** [comment]
fixed with cb73a486c06c9e792f7f0af475ca439dcaa4362c
Blind with deviceId=1013 runs on channel ch003

**Comment by ruebox** [comment]
please check new snapshot #14
